---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: nginx-pipeline
description: Nginx Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: dev
  - targetId: uat
  - targetId: prod

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: dev Environment
run:
  location: projects/yougo-dev-369515/locations/us-central1

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: uat
description: UAT Environment
run:
  location: projects/uat-cluster-371515/locations/us-central1

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: prod Environment
requireApproval: true
run:
  location: projects/yougo-prod-369515/locations/us-east1
